---

- name: 'openstack_heat.tasks.configuration: Configure heat api'
  ini_file:
    dest: '/etc/heat/heat.conf'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - section: 'database'
      option: 'connection'
      value: '{{ openstack_heat_database_url }}'

    - section: 'DEFAULT'
      option: 'rpc_backend'
      value: 'rabbit'
    - section: 'oslo_messaging_rabbit'
      option: 'rabbit_host'
      value: '{{ openstack_heat_rabbit_hostname }}'
    - section: 'oslo_messaging_rabbit'
      option: 'rabbit_userid'
      value: '{{ openstack_heat_rabbit_username }}'
    - section: 'oslo_messaging_rabbit'
      option: 'rabbit_password'
      value: '{{ openstack_heat_rabbit_pass }}'
    - section: 'oslo_messaging_rabbit'
      option: 'rabbit_virtual_host'
      value: '{{ openstack_heat_rabbit_virtual_host }}'

    - section: 'keystone_authtoken'
      option: 'identity_uri'
      value: '{{ openstack_heat_keystone_protocol }}://{{ openstack_heat_keystone_hostname }}:{{ openstack_heat_keystone_admin_port }}'
    - section: 'keystone_authtoken'
      option: 'auth_uri'
      value: '{{ openstack_heat_keystone_protocol }}://{{ openstack_heat_keystone_hostname }}:{{ openstack_heat_keystone_port }}/v3'
    - section: 'keystone_authtoken'
      option: 'auth_url'
      value: '{{ openstack_heat_keystone_protocol }}://{{ openstack_heat_keystone_hostname }}:{{ openstack_heat_keystone_admin_port }}'
    - section: 'keystone_authtoken'
      option: 'auth_type'
      value: 'password'
    - section: 'keystone_authtoken'
      option: 'project_domain_name'
      value: 'default'
    - section: 'keystone_authtoken'
      option: 'user_domain_name'
      value: 'default'
    - section: 'keystone_authtoken'
      option: 'project_name'
      value: 'service'
    - section: 'keystone_authtoken'
      option: 'username'
      value: 'heat'
    - section: 'keystone_authtoken'
      option: 'password'
      value: '{{ openstack_heat_pass }}'
    - section: 'keystone_authtoken'
      option: 'memcached_servers'
      value: '{{ openstack_heat_keystone_hostname }}:11211'
    - section: 'keystone_authtoken'
      option: 'auth_version'
      value: 'v3'

    - section: 'trustee'
      option: 'auth_plugin'
      value: 'password'
    - section: 'trustee'
      option: 'auth_url'
      value: '{{ openstack_heat_keystone_protocol }}://{{ openstack_heat_keystone_hostname }}:{{ openstack_heat_keystone_admin_port }}'
    - section: 'trustee'
      option: 'username'
      value: 'heat'
    - section: 'trustee'
      option: 'password'
      value: '{{ openstack_heat_pass }}'
    - section: 'trustee'
      option: 'user_domain_name'
      value: 'default'

    - section: 'clients_keystone'
      option: 'auth_uri'
      value: '{{ openstack_heat_keystone_protocol }}://{{ openstack_heat_keystone_hostname }}:{{ openstack_heat_keystone_admin_port }}'

    - section: 'ec2authtoken'
      option: 'auth_uri'
      value: '{{ openstack_heat_keystone_protocol }}://{{ openstack_heat_keystone_hostname }}:{{ openstack_heat_keystone_port }}/v3'

    - section: 'DEFAULT'
      option: 'heat_metadata_server_url'
      value: '{{ openstack_heat_metadata_server_url }}'
    - section: 'DEFAULT'
      option: 'heat_waitcondition_server_url'
      value: '{{ openstack_heat_waitcondition_server_url }}'

    - section: 'DEFAULT'
      option: 'stack_domain_admin'
      value: 'heat_domain_admin'
    - section: 'DEFAULT'
      option: 'stack_domain_admin_password'
      value: '{{ openstack_heat_pass }}'
    - section: 'DEFAULT'
      option: 'stack_user_domain_name'
      value: 'heat'
  notify:
    - 'openstack_heat.handlers.main: Restart heat services'
