---

- name: 'openstack_heat.tasks.facts: Set service facts for Debian family'
  set_fact:
    openstack_heat_api_service: 'heat-api'
    openstack_heat_api_cfn_service: 'heat-api-cfn'
    openstack_heat_engine_service: 'heat-engine'
    openstack_heat_database_migration_repository: >-
      /usr/lib/python2.7/dist-packages/heat/db/sqlalchemy/migrate_repo/versions
  when: ansible_os_family == 'Debian'

- name: 'openstack_heat.tasks.facts: Set service facts for RedHat family'
  set_fact:
    openstack_heat_api_service: 'openstack-heat-api'
    openstack_heat_api_cfn_service: 'openstack-heat-api-cfn'
    openstack_heat_engine_service: 'openstack-heat-engine'
    openstack_heat_database_migration_repository: >-
      /usr/lib/python2.7/site-packages/heat/db/sqlalchemy/migrate_repo/versions
  when: ansible_os_family == 'RedHat'
