---

- name: 'openstack_heat.handlers.main: Restart heat services'
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - '{{ openstack_heat_api_service }}'
    - '{{ openstack_heat_api_cfn_service }}'
    - '{{ openstack_heat_engine_service }}'
